# Generated by Django 3.2.5 on 2021-07-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(blank=True),
        ),
    ]
